exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: AGPL-3.0
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/surveychat/surveychat"

title: surveychat
description: Open-source chatbot tools for researchers
